services:
  postgres:
    image: postgres:15
    container_name: postgres_server
    environment:
      POSTGRES_USER: costigan
      POSTGRES_PASSWORD: BillyCostigan
      POSTGRES_DB: gym_hibernate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_client
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
